### PR TITLE
Script to collect contributors statistics.

### PR DESCRIPTION
**Pull request by freyes**
The release-contributors.sh script prints the list of contributors in alphabetical order using "git log" and a baseline branch to compare against master

Usage example of contributors to the Ceph, OVN and OpenStack charms since Quincy, 22.03 and Yoga releases respectively.

    ./release-contributors.sh \
        --os-baseline yoga \
	--ovn-baseline 22.03 \
	--ceph-baseline quincy \
	--libs-dir ./git/openstack-charms

Co-Authored-By: Peter Matulis <peter.matulis@canonical.com>

### CODE REVIEW

**Comment by freyes** [comment]
output example: https://pastebin.ubuntu.com/p/nrMyJ9QCRc/

**Comment by pmatulis** [comment]
The `SUMMARY_FILE` variable is not being used.

I would prefer the output to not be directed to STDOUT and instead a note added that points to the output file.

**Comment by freyes** [comment]
I added a new flag "--output contributors.txt" that allows you to write the list of contributors to
a file instead of to stdout,
see https://github.com/openstack-charmers/release-tools/pull/270/commits/baea43a2770a47aec59da3920b39d8b8071afa6b

does this look ok to you?

**Review by ajkavanagh — APPROVED** [review]
LGTM

**Pull request merged**
