### PR TITLE
Update push-and-release to fail when push fails

### PR DESCRIPTION
**Pull request by ryan-beisner**

### CODE REVIEW

**Comment by ryan-beisner** [comment]
Example of what we are fixing:

```
 . Releasing charm cs:~openstack-charmers/keystone-ldap-2
ERROR cannot release charm or bundle: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot release charm or bundle: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot release charm or bundle: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot release charm or bundle: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot release charm or bundle: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot release charm or bundle: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot release charm or bundle: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot release charm or bundle: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot release charm or bundle: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot release charm or bundle: unauthorized: access denied for user "uosci-testing-bot"
 . Granting global read acl
ERROR cannot set permissions: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot set permissions: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot set permissions: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot set permissions: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot set permissions: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot set permissions: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot set permissions: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot set permissions: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot set permissions: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot set permissions: unauthorized: access denied for user "uosci-testing-bot"
 . Setting charm homepage and bugs-url options
ERROR cannot update the set arguments provided: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot update the set arguments provided: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot update the set arguments provided: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot update the set arguments provided: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot update the set arguments provided: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot update the set arguments provided: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot update the set arguments provided: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot update the set arguments provided: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot update the set arguments provided: unauthorized: access denied for user "uosci-testing-bot"
ERROR cannot update the set arguments provided: unauthorized: access denied for user "uosci-testing-bot"
 . Charm store refs released:
cs:~openstack-charmers/keystone-ldap-2
'/tmp/tmp.JC94gQv4T6' -> '/var/lib/jenkins/workspace/charm_pusher_keystone-ldap_stable/cs_refs_released.txt'
 - Unsetting HTTP(S) proxies if set.
BUILD_DIR: /var/lib/jenkins/workspace/charm_pusher_keystone-ldap_stable/keystone-ldap/build
Removing /var/lib/jenkins/workspace/charm_pusher_keystone-ldap_stable/keystone-ldap/build
====>  end charm push  <=======================
====>  Cleaning up /tmp (Safe to ignore file/dir permission errors)  <=======================
find: ‘/tmp/tmux-0’: Permission denied
find: ‘/tmp/systemd-private-ce779a405b46420b94c053445f9f6013-systemd-timesyncd.service-c3mT3W’: Permission denied
Archiving artifacts
Recording fingerprints
Email was triggered for: Success
Sending email for trigger: Success
Sending email to: openstack-charm-ci-watchers@lists.launchpad.net
Connection error sending email, retrying once more in 10 seconds...
Connection error sending email, retrying once more in 10 seconds...
Failed after second try sending email
Finished: SUCCESS
```

**Comment by thedac** [comment]
It seems to me that line will never be true. The while loop is less than attempts. It will never be greater or equal to attempts.

**Comment by ryan-beisner** [comment]
Ah, but it will, because it is after:

let "i+=1"

Tested and it works.

**Comment by thedac** [comment]
Excellent point. Merging.

**Pull request merged**
